name: Build Pull Request

on:
  pull-request:
    paths-ignore:
      - 'README.md'

env:
  PUID: '1000'
  PGID: '1000'
  PHP_TZ: 'UTC'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          load: true
          tags: |
            lycheeorg/lychee:testing-${{ github.run_id }}
      -
        name: Export Image and PR Number
        run: |
          mkdir -p ./artifact
          docker export -o ./artifact/lychee.tar lycheeorg/lychee:testing-${{ github.run_id }}
          echo ${{ github.event.number }} > ./artifact/pr
      - 
        name: Store as artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ./artifact
